package chatapp;

import javax.swing.*;
import java.io.*;
import java.net.*;

/**
 *
 * @author Tamanna Qureshi
 */
public class Chat_Client extends javax.swing.JFrame {

    /**
     * Creates new form Chat_Client
     */
    static Socket clientSocket;
    static DataInputStream clientInputStream;
    static DataOutputStream clientOutputStream;
    
    public Chat_Client() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        messageAreaClient = new javax.swing.JTextArea();
        textBoxClient = new javax.swing.JTextField();
        SendButtonClient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client");
        setMinimumSize(new java.awt.Dimension(537, 482));

        messageAreaClient.setColumns(20);
        messageAreaClient.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        messageAreaClient.setRows(5);
        jScrollPane1.setViewportView(messageAreaClient);

        textBoxClient.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        SendButtonClient.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        SendButtonClient.setText("Send");
        SendButtonClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendButtonClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textBoxClient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SendButtonClient)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBoxClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SendButtonClient))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SendButtonClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendButtonClientActionPerformed
        String msgClient = "";
        try
        {
            msgClient = textBoxClient.getText().trim();
            clientOutputStream.writeUTF(msgClient);
        }
        catch(Exception e)
        {
            //handle exception here
        }
    }//GEN-LAST:event_SendButtonClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chat_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chat_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chat_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chat_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chat_Client().setVisible(true);
            }
        });
        
        try
        {
            clientSocket = new Socket("127.0.0.1",1201);
            clientInputStream = new DataInputStream(clientSocket.getInputStream());
            clientOutputStream = new DataOutputStream(clientSocket.getOutputStream());
            String msgclient = "";
            while(!msgclient.equals("exit"))
            {
                msgclient = clientInputStream.readUTF();
                messageAreaClient.setText(messageAreaClient.getText().trim() + "\nServer:\t" + msgclient);
            }
        }
        catch(Exception e)
        {
            //handle this exception
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton SendButtonClient;
    public javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea messageAreaClient;
    public javax.swing.JTextField textBoxClient;
    // End of variables declaration//GEN-END:variables
}
